luxo:
    controller:
      state:
        type: joint_state_controller/JointStateController
        publish_rate: 50

      trajectory:
          type: position_controllers/JointTrajectoryController
          joints:
              - foot
              - knee
              - ass
              - neck
              - head
          gains:
              foot: { p: 0.1, i: 0.0, d: 0.0, i_clamp: 1.0 }
              knee: { p: 0.1, i: 0.0, d: 0.0, i_clamp: 1.0 }
              ass: { p: 0.1, i: 0.0, d: 0.0, i_clamp: 1.0 }
              neck: { p: 0.1, i: 0.0, d: 0.0, i_clamp: 1.0 }
              head: { p: 0.1, i: 0.0, d: 0.0, i_clamp: 1.0 }

      position:
          foot:
                type: position_controllers/JointPositionController
                joint: foot
                pid: {p: 0.1, i: 0.0, d: 0.0}

          knee:
                type: position_controllers/JointPositionController
                joint: knee
                pid: {p: 0.1, i: 0.0, d: 0.0}

          ass:
                type: position_controllers/JointPositionController
                joint: ass
                pid: {p: 0.1, i: 0.0, d: 0.0}

          neck:
                type: position_controllers/JointPositionController
                joint: neck
                pid: {p: 0.1, i: 0.0, d: 0.0}

          head:
                type: position_controllers/JointPositionController
                joint: head
                pid: {p: 0.1, i: 0.0, d: 0.0}

