luxo:
  hardware_interface:
    loop_hz: 50
    joints:
      - foot
      - knee
      - ass
      - neck
      - head
    initial_states:
      foot: 0.5
      knee: 0.3
      ass: 0.3
      neck: 1.0
      head: 0.5
    pwm:
      foot:
        min: 3000
        max: 7600
        channel: 0
      knee:
        min: 3200
        max: 7000
        channel: 1
      ass:
        min: 4100
        max: 6800
        channel: 2
      neck:
        min: 3000
        max: 7600
        channel: 3
      head:
        min: 3000
        max: 7600
        channel: 4
