joint_limits:
        foot:
                has_position_limits: true
                min_position: 0.1
                max_position: 0.9
                has_velocity_limits: true
                max_velocity: 1.0
                has_acceleration_limits: true
                max_acceleration: 0.1
                has_jerk_limits: true
                max_jerk: 1.0
                has_effort_limits: false
        knee:
                has_position_limits: true
                min_position: 0.2
                max_position: 0.8
                has_velocity_limits: true
                max_velocity: 1.0
                has_acceleration_limits: true
                max_acceleration: 1.0
                has_jerk_limits: true
                max_jerk: 1.0
                has_effort_limits: false
        ass:
                has_position_limits: true
                min_position: 0.2
                max_position: 0.8
                has_velocity_limits: true
                max_velocity: 1.0
                has_acceleration_limits: true
                max_acceleration: 1.0
                has_jerk_limits: true
                max_jerk: 1.0
                has_effort_limits: false
        neck:
                has_position_limits: true
                min_position: 0.0
                max_position: 0.5
                has_velocity_limits: true
                max_velocity: 1.0
                has_acceleration_limits: true
                max_acceleration: 1.0
                has_jerk_limits: true
                max_jerk: 1.0
                has_effort_limits: false
        head:
                has_position_limits: true
                min_position: 0.2
                max_position: 0.7
                has_velocity_limits: true
                max_velocity: 1.0
                has_acceleration_limits: true
                max_acceleration: 1.0
                has_jerk_limits: true
                max_jerk: 1.0
                has_effort_limits: false

